### ISSUE TITLE
Blocked on Cliffsides ISO with certain seed

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#419]
**Description**
Encountered a strange bug where upon starting Cliffsides, the Action List would show the previous scene's actions (Arabia) and then the first object in the Prev Bubble is Tent > Purple. However, the game will not accept this item, and so you're stuck. 

**To Reproduce**
Seed: D15C0F9B8FDFDCBC1D92452D2C226BFE0B
1. Setup Seed, play through Arabian
2. Start Cliffsides, see that the action list is the same as before. 
3. Play Cliffsides, try to select Tent>Purple
4. Game doesn't register item as accepted

**Screenshots**

![image](https://user-images.githubusercontent.com/6446247/58923938-9fa55480-86f6-11e9-8ed7-3cee5825ce86.png)

**Device Info (please complete the following information):**
 - Version 6-4-2019

**Comment by westonb7** [comment]
There seems to be problems like this with a number of scenes - apparently some recent change (in the dev branch, at least) is causing some interactables to be 'out of bounds'. For this specific seed, it's because the cliffside scene thinks it only has 15 interactables, not 16.

The Cliffsides scene is having problems finding the 'Survival Guide' interactable, causing the above issue.

Additionally, in the wizard tower, the 'Send Letter' and 'Feed Dragon Baby' interactables can't be found either - so some recent change has cause these interactables to have problems with the rest of the scene.

I'll look into what the source is and find a fix for it.
