### ISSUE TITLE
Interactable UI Update

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#436]
**Is your feature request related to a problem? Please describe.**
Need to improve the interactable label UI

**Describe the solution you'd like**
Default state: Show both the name of the interactable 
Hover/Active State: Show both name / actions for interactable. Have name be in above the interactable, and have the actions below the interactable

Change interactable ui text from in-world space to screen space

**Comment by westonb7** [comment]
Interactable UIs have been updated. Now both interactable name and actions are shown at the same time - with the name above the interactable and the actions below the interactable. This is disabled by default, and can be re-enabled by toggling the "Use interactable name" and "Use separated UI" toggles in the interactable manager component of the GameSystems object.

<img width="280" alt="Screen Shot 2019-08-07 at 7 54 51 AM" src="https://user-images.githubusercontent.com/30869523/62628601-d65f3d00-b8e8-11e9-8948-e859dca6d68f.png">

By default, the scripts will try to "guess" where the interactable name and action should be. Since many interactable labels are placed differently for each interactable, each needs to be set up to look right. The interactable script now has a few more offset parameters for where to put the label for the interactable name (position offset), as well as where to put the button for the interactable (low position offset).

<img width="297" alt="Screen Shot 2019-08-07 at 7 52 28 AM" src="https://user-images.githubusercontent.com/30869523/62628771-31912f80-b8e9-11e9-9667-579bb6fc3d67.png">
